name: 'TPM Agent'
description: 'A reusable GitHub Action for TPM-related operations using Semantic Kernel'
author: 'Matt Dotson'

inputs:
  issue_content:
    description: 'The content of the GitHub issue to process'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  repository:
    description: 'Repository in the format owner/repo'
    required: true
  issue_number:
    description: 'Issue number to comment on'
    required: true

outputs:
  result:
    description: 'Result of the operation'
  status:
    description: 'Status of the operation'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'shield'
  color: 'blue'